Repository truongduchuy910/PBL6, pull requests merged in 2021-11, with the labels that each got.

#72 hook-after-create-comment
  schemas/Interactive/Comment/hook.js
  schemas/Interactive/Comment/index.js
  schemas/Post/hook.js
  schemas/Post/index.js
Labels: 100%

#85 fixed bug avatar user in post, refetch comments
  .gitignore
  app/ui/Interactive/Comment/Create/Controller.js
  app/ui/Interactive/Comment/Delete/Controller.js
  app/ui/Interactive/Create/Controller.js
  app/ui/Interactive/Item/Controller.js
  app/ui/Interactive/Item/Simple.js
  app/ui/Post/Item/Simple.js
Labels: 100%, ưu tiên cao

#91 Thích Bài viết
  app/ui/Interactive/Item/Simple.js
  app/ui/Interactive/Reaction/Create/Button.js
  app/ui/Interactive/Reaction/Create/Controller.js
  app/ui/Interactive/Reaction/Create/Text.js
  app/ui/Interactive/Reaction/List/Controller.js
  app/ui/Interactive/Reaction/List/IconTextWithCount.js
  app/ui/Interactive/Reaction/List/TextWithCount.js
  app/ui/Post/Item/Controller.js
  app/ui/Post/Item/Simple.js
Labels: 100%

#93 Hook inter
  schemas/Interactive/Comment/hook.js
  schemas/Interactive/Comment/index.js
  schemas/Interactive/Reaction/index.js
  schemas/Interactive/hook.js
  schemas/Interactive/index.js
  schemas/Post/hook.js
Labels: 25%

#125 Fix UI on personal page
  app/package.json
  app/ui/User/Item/Detail.js
  app/yarn.lock
Labels: 100%
